<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1595622274036' stop='1595622381004'>
    <name>Free blocks</name>
    <title>Free blocks</title>
    <test-cases>
        <test-case start='1595622313100' status='failed' stop='1595622347127'>
            <name>Pinterest block</name>
            <title>Pinterest block</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1595622313102' status='undefined'>
                    <name>Can visit the block editor and add a Pinterest block</name>
                    <title>Can visit the block editor and add a Pinterest block</title>
                    <attachments>
                        <attachment title='Test failed: Free blocks :: Pinterest block' source='2708c526-5290-465f-8380-08fef4047736-attachment.png' type='image/png' size='44369'/>
                    </attachments>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Error: Command failed: yarn wp-env run tests-wordpress cat wp-content/debug.log
                ℹ Starting 'cat wp-content/debug.log' on the tests-wordpress container. 
                
                Starting 5c5d92595c30b14aa520446a7eafd734_mysql_1_a3359e0d9f67 ... 
                Starting 5c5d92595c30b14aa520446a7eafd734_mysql_1_a3359e0d9f67 ... donecat: wp-content/debug.log: No such file or directory
                ✖ Command failed with exit code 1
                Command failed with exit code 1
                error Command failed with exit code 1.
                </message>
                <stack-trace>Error: Command failed: yarn wp-env run tests-wordpress cat wp-content/debug.log
                ℹ Starting 'cat wp-content/debug.log' on the tests-wordpress container. 
                
                Starting 5c5d92595c30b14aa520446a7eafd734_mysql_1_a3359e0d9f67 ... 
                Starting 5c5d92595c30b14aa520446a7eafd734_mysql_1_a3359e0d9f67 ... donecat: wp-content/debug.log: No such file or directory
                ✖ Command failed with exit code 1
                Command failed with exit code 1
                error Command failed with exit code 1.
                
                    at checkExecSyncError (child_process.js:630:11)
                    at execSync (child_process.js:666:15)
                    at execSyncShellCommand (/home/travis/build/Automattic/jetpack/tests/e2e/lib/utils-helper.js:27:9)
                    at _callee10$ (/home/travis/build/Automattic/jetpack/tests/e2e/lib/page-helper.js:209:9)
                    at tryCatch (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.&lt;computed> [as next] (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
                    at /home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7</stack-trace>
            </failure>
        </test-case>
        <test-case start='1595622347127' status='failed' stop='1595622381004'>
            <name>Eventbrite block</name>
            <title>Eventbrite block</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1595622347128' status='undefined'>
                    <name>Can visit the block editor and add a Eventbrite block</name>
                    <title>Can visit the block editor and add a Eventbrite block</title>
                    <attachments>
                        <attachment title='Test failed: Free blocks :: Eventbrite block' source='d18933e9-c479-4e10-8c40-39a666b34993-attachment.png' type='image/png' size='44394'/>
                    </attachments>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Error: Command failed: yarn wp-env run tests-wordpress cat wp-content/debug.log
                ℹ Starting 'cat wp-content/debug.log' on the tests-wordpress container. 
                
                Starting 5c5d92595c30b14aa520446a7eafd734_mysql_1_a3359e0d9f67 ... 
                Starting 5c5d92595c30b14aa520446a7eafd734_mysql_1_a3359e0d9f67 ... donecat: wp-content/debug.log: No such file or directory
                ✖ Command failed with exit code 1
                Command failed with exit code 1
                error Command failed with exit code 1.
                </message>
                <stack-trace>Error: Command failed: yarn wp-env run tests-wordpress cat wp-content/debug.log
                ℹ Starting 'cat wp-content/debug.log' on the tests-wordpress container. 
                
                Starting 5c5d92595c30b14aa520446a7eafd734_mysql_1_a3359e0d9f67 ... 
                Starting 5c5d92595c30b14aa520446a7eafd734_mysql_1_a3359e0d9f67 ... donecat: wp-content/debug.log: No such file or directory
                ✖ Command failed with exit code 1
                Command failed with exit code 1
                error Command failed with exit code 1.
                
                    at checkExecSyncError (child_process.js:630:11)
                    at execSync (child_process.js:666:15)
                    at execSyncShellCommand (/home/travis/build/Automattic/jetpack/tests/e2e/lib/utils-helper.js:27:9)
                    at _callee10$ (/home/travis/build/Automattic/jetpack/tests/e2e/lib/page-helper.js:209:9)
                    at tryCatch (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.&lt;computed> [as next] (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
                    at /home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>