<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1609974941784' stop='1609975035395'>
    <name>Free blocks</name>
    <title>Free blocks</title>
    <test-cases>
        <test-case start='1609974977616' status='failed' stop='1609975006547'>
            <name>Pinterest block</name>
            <title>Pinterest block</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1609974977617' status='undefined'>
                    <name>Can visit the block editor and add a Pinterest block</name>
                    <title>Can visit the block editor and add a Pinterest block</title>
                    <attachments>
                        <attachment title='Test failed: Free blocks :: Pinterest block' source='b4327ec9-ba6f-42a3-aa33-489bfaf11b27-attachment.png' type='image/png' size='4806'/>
                    </attachments>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Error: Site does not have free plan</message>
                <stack-trace>Error: Site does not have free plan
                    at _callee4$ (/home/runner/work/jetpack/jetpack/tests/e2e/lib/flows/jetpack-connect.js:109:9)
                    at tryCatch (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.&lt;computed> [as next] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1609975006548' status='failed' stop='1609975035394'>
            <name>Eventbrite block</name>
            <title>Eventbrite block</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1609975006548' status='undefined'>
                    <name>Can visit the block editor and add a Eventbrite block</name>
                    <title>Can visit the block editor and add a Eventbrite block</title>
                    <attachments>
                        <attachment title='Test failed: Free blocks :: Eventbrite block' source='d75d3743-6362-4abd-ab9a-dfa542458ac4-attachment.png' type='image/png' size='4806'/>
                    </attachments>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Error: Site does not have free plan</message>
                <stack-trace>Error: Site does not have free plan
                    at _callee4$ (/home/runner/work/jetpack/jetpack/tests/e2e/lib/flows/jetpack-connect.js:109:9)
                    at tryCatch (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.&lt;computed> [as next] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>