<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1604669382858' stop='1604669482643'>
    <name>Paid blocks</name>
    <title>Paid blocks</title>
    <test-cases>
        <test-case start='1604669389846' status='failed' stop='1604669419346'>
            <name>MailChimp Block</name>
            <title>MailChimp Block</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1604669389847' status='undefined'>
                    <name>Can visit the block editor and add a MailChimp block</name>
                    <title>Can visit the block editor and add a MailChimp block</title>
                    <attachments>
                        <attachment title='Test failed: Paid blocks :: MailChimp Block' source='1ca6cd49-cffb-4cb9-992e-7bb04ee3709c-attachment.png' type='image/png' size='22663'/>
                    </attachments>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>TimeoutError: Navigation timeout of 30000 ms exceeded</message>
                <stack-trace>TimeoutError: Navigation timeout of 30000 ms exceeded
                    at /home/runner/work/jetpack/jetpack/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
                  -- ASYNC --
                    at Frame.&lt;anonymous> (/home/runner/work/jetpack/jetpack/node_modules/puppeteer/lib/helper.js:111:15)
                    at Page.goto (/home/runner/work/jetpack/jetpack/node_modules/puppeteer/lib/Page.js:672:49)
                    at Page.&lt;anonymous> (/home/runner/work/jetpack/jetpack/node_modules/puppeteer/lib/helper.js:112:23)
                    at Function.goto (/home/runner/work/jetpack/jetpack/tests/e2e/lib/pages/page.js:44:14)
                    at tryCatch (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.&lt;computed> [as next] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
                    at /home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
                  -- ASYNC --
                    at Page.&lt;anonymous> (/home/runner/work/jetpack/jetpack/node_modules/puppeteer/lib/helper.js:111:15)
                    at Function.goto (/home/runner/work/jetpack/jetpack/tests/e2e/lib/pages/page.js:44:14)
                    at tryCatch (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.&lt;computed> [as next] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
                    at /home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
                    at new Promise (&lt;anonymous>)
                    at Function.&lt;anonymous> (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1604669419346' status='failed' stop='1604669448860'>
            <name>Pay with PayPal</name>
            <title>Pay with PayPal</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1604669419347' status='undefined'>
                    <name>Can visit the block editor and add a Pay with PayPal block</name>
                    <title>Can visit the block editor and add a Pay with PayPal block</title>
                    <attachments>
                        <attachment title='Test failed: Paid blocks :: Pay with PayPal' source='c4c5e883-b9a7-4b3a-87ce-01dacd55c6e6-attachment.png' type='image/png' size='22663'/>
                    </attachments>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>TimeoutError: Navigation timeout of 30000 ms exceeded</message>
                <stack-trace>TimeoutError: Navigation timeout of 30000 ms exceeded
                    at /home/runner/work/jetpack/jetpack/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
                  -- ASYNC --
                    at Frame.&lt;anonymous> (/home/runner/work/jetpack/jetpack/node_modules/puppeteer/lib/helper.js:111:15)
                    at Page.goto (/home/runner/work/jetpack/jetpack/node_modules/puppeteer/lib/Page.js:672:49)
                    at Page.&lt;anonymous> (/home/runner/work/jetpack/jetpack/node_modules/puppeteer/lib/helper.js:112:23)
                    at Function.goto (/home/runner/work/jetpack/jetpack/tests/e2e/lib/pages/page.js:44:14)
                    at tryCatch (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.&lt;computed> [as next] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
                    at /home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
                  -- ASYNC --
                    at Page.&lt;anonymous> (/home/runner/work/jetpack/jetpack/node_modules/puppeteer/lib/helper.js:111:15)
                    at Function.goto (/home/runner/work/jetpack/jetpack/tests/e2e/lib/pages/page.js:44:14)
                    at tryCatch (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.&lt;computed> [as next] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
                    at /home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
                    at new Promise (&lt;anonymous>)
                    at Function.&lt;anonymous> (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1604669448860' status='failed' stop='1604669479205'>
            <name>WordAds block</name>
            <title>WordAds block</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1604669448861' status='undefined'>
                    <name>Can visit the block editor and add a WordAds block</name>
                    <title>Can visit the block editor and add a WordAds block</title>
                    <attachments>
                        <attachment title='Test failed: Paid blocks :: WordAds block' source='8a82561b-e799-473c-8ade-107558b6fd09-attachment.png' type='image/png' size='22663'/>
                    </attachments>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>TimeoutError: Navigation timeout of 30000 ms exceeded</message>
                <stack-trace>TimeoutError: Navigation timeout of 30000 ms exceeded
                    at /home/runner/work/jetpack/jetpack/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
                  -- ASYNC --
                    at Frame.&lt;anonymous> (/home/runner/work/jetpack/jetpack/node_modules/puppeteer/lib/helper.js:111:15)
                    at Page.goto (/home/runner/work/jetpack/jetpack/node_modules/puppeteer/lib/Page.js:672:49)
                    at Page.&lt;anonymous> (/home/runner/work/jetpack/jetpack/node_modules/puppeteer/lib/helper.js:112:23)
                    at Function.goto (/home/runner/work/jetpack/jetpack/tests/e2e/lib/pages/page.js:44:14)
                    at tryCatch (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.&lt;computed> [as next] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
                    at /home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
                  -- ASYNC --
                    at Page.&lt;anonymous> (/home/runner/work/jetpack/jetpack/node_modules/puppeteer/lib/helper.js:111:15)
                    at Function.goto (/home/runner/work/jetpack/jetpack/tests/e2e/lib/pages/page.js:44:14)
                    at tryCatch (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.&lt;computed> [as next] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
                    at /home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
                    at new Promise (&lt;anonymous>)
                    at Function.&lt;anonymous> (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>