<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1604106010164' stop='1604106032093'>
    <name>Jetpack pre-connection</name>
    <title>Jetpack pre-connection</title>
    <test-cases>
        <test-case start='1604106013632' status='passed' stop='1604106017567'>
            <name>Can find connect button on plugins page</name>
            <title>Can find connect button on plugins page</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1604106017567' status='passed' stop='1604106018077'>
            <name>Can find connect button on dashboard page</name>
            <title>Can find connect button on dashboard page</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1604106018077' status='failed' stop='1604106031434'>
            <name>Can find connect button on Jetpack page</name>
            <title>Can find connect button on Jetpack page</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Test failed: Jetpack pre-connection :: Can find connect button on Jetpack page' source='8b1d2f90-b464-4377-b47b-bca516716f49-attachment.png' type='image/png' size='29530'/>
            </attachments>
            <failure>
                <message>Error: expect(received).toBeTruthy()
                
                Received: false</message>
                <stack-trace>Error: expect(received).toBeTruthy()
                
                Received: false
                    at toBeTruthy (/home/runner/work/jetpack/jetpack/tests/e2e/specs/pre-connection.test.js:47:56)
                    at tryCatch (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.&lt;computed> [as next] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>