<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1607639523867' stop='1607639585187'>
    <name>Free blocks</name>
    <title>Free blocks</title>
    <test-cases>
        <test-case start='1607639568836' status='failed' stop='1607639577361'>
            <name>Pinterest block</name>
            <title>Pinterest block</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1607639568837' status='passed' stop='1607639573169'>
                    <name>Can visit the block editor and add a Pinterest block</name>
                    <title>Can visit the block editor and add a Pinterest block</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1607639573169' status='passed' stop='1607639576801'>
                    <name>Can publish a post with a Pinterest block</name>
                    <title>Can publish a post with a Pinterest block</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1607639576801' status='passed' stop='1607639577357'>
                    <name>Can assert that Pinterest block is rendered</name>
                    <title>Can assert that Pinterest block is rendered</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Error: Site does not have free plan</message>
                <stack-trace>Error: Site does not have free plan
                    at _callee4$ (/home/runner/work/jetpack/jetpack/tests/e2e/lib/flows/jetpack-connect.js:109:9)
                    at tryCatch (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.&lt;computed> [as next] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1607639577361' status='failed' stop='1607639585187'>
            <name>Eventbrite block</name>
            <title>Eventbrite block</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1607639577362' status='passed' stop='1607639581879'>
                    <name>Can visit the block editor and add a Eventbrite block</name>
                    <title>Can visit the block editor and add a Eventbrite block</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1607639581879' status='passed' stop='1607639584846'>
                    <name>Can publish a post with a Eventbrite block</name>
                    <title>Can publish a post with a Eventbrite block</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1607639584846' status='passed' stop='1607639585182'>
                    <name>Can assert that Eventbrite block is rendered</name>
                    <title>Can assert that Eventbrite block is rendered</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Error: Site does not have free plan</message>
                <stack-trace>Error: Site does not have free plan
                    at _callee4$ (/home/runner/work/jetpack/jetpack/tests/e2e/lib/flows/jetpack-connect.js:109:9)
                    at tryCatch (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.&lt;computed> [as next] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>